In [20]:
import torch
import torch.nn as nn

In [21]:
input=torch.tensor([
[73,67,43],
[91,88,64],
[87,134,58],
[102,43,37],
[69,96,70],
[74,66,43],
[91,87,65],
[88,134,59],
[101,44,37],
[68,96,71],
[73,66,44],
[92,87,64],
[87,135,57],
[103,43,36],
[68,97,70]
],dtype=torch.float32)
print(input.dtype)
print(input.shape)

torch.float32
torch.Size([15, 3])


In [22]:
target=torch.tensor([
[56,70],
[81,101],
[119,113],
[22,37],
[103,119],
[57,69],
[80,102],
[118,132],
[21,38],
[104,118],
[57,69],
[82,100],
[118,134],
[20,38],
[102,120]
],dtype=torch.float32)
print(target.dtype)
print(target.shape)

torch.float32
torch.Size([15, 2])


In [23]:
from torch.utils.data import TensorDataset
train_ds=TensorDataset(input,target)
train_ds[3]

(tensor([102.,  43.,  37.]), tensor([22., 37.]))

In [24]:
from torch.utils.data import DataLoader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)
for a,b in train_dl:
    print(a)
    print(b)
    break

tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [103., 119.],
        [102., 120.],
        [ 21.,  38.],
        [ 22.,  37.]])


calculate the predctions

In [25]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2259, -0.3174, -0.2916],
        [ 0.0251, -0.4821,  0.0691]], requires_grad=True)
Parameter containing:
tensor([ 0.1395, -0.0355], requires_grad=True)


In [26]:
preds=model(input)
preds

tensor([[-17.1692, -27.5308],
        [-25.8906, -35.7512],
        [-39.6434, -58.4434],
        [ -1.2505, -15.6465],
        [-35.1498, -39.7459],
        [-16.6259, -27.0235],
        [-25.8648, -35.2000],
        [-39.7090, -58.3492],
        [ -1.7938, -16.1538],
        [-35.6674, -39.7019],
        [-17.1434, -26.9795],
        [-25.3473, -35.2440],
        [-39.6691, -58.9947],
        [ -0.7329, -15.6906],
        [-35.6931, -40.2531]], grad_fn=<AddmmBackward0>)

calculate the mean square error(MSE)

In [27]:
import torch.nn.functional as f
loss_fn=f.mse_loss
loss=loss_fn(preds,target)
loss

tensor(15178.0215, grad_fn=<MseLossBackward0>)

compute the gradient

In [28]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [29]:
def fit(num_epochs):
    for epoch in range(num_epochs):
        for a,b in train_dl:
            preds=model(a)
            loss=loss_fn(preds,b)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) %10==0:
            print("current epoch / total epochs done : [{}/{}] ,current loss : {}".format(epoch+1,num_epochs,loss.item()))
    

In [30]:
fit(100)

current epoch / total epochs done : [10/100] ,current loss : 246.3782196044922
current epoch / total epochs done : [20/100] ,current loss : 746.6212158203125
current epoch / total epochs done : [30/100] ,current loss : 283.3976745605469
current epoch / total epochs done : [40/100] ,current loss : 426.6549377441406
current epoch / total epochs done : [50/100] ,current loss : 45.295066833496094
current epoch / total epochs done : [60/100] ,current loss : 42.71321487426758
current epoch / total epochs done : [70/100] ,current loss : 137.5131072998047
current epoch / total epochs done : [80/100] ,current loss : 88.04792022705078
current epoch / total epochs done : [90/100] ,current loss : 90.79582214355469
current epoch / total epochs done : [100/100] ,current loss : 60.15643310546875


In [31]:
preds=model(input)
preds

tensor([[ 58.7553,  70.7608],
        [ 79.9829,  98.5021],
        [119.6611, 127.9784],
        [ 31.0733,  46.7141],
        [ 92.3592, 110.3649],
        [ 57.7045,  69.9477],
        [ 79.3706,  98.4593],
        [119.7647, 128.5649],
        [ 32.1241,  47.5273],
        [ 92.7976, 111.1353],
        [ 58.1429,  70.7180],
        [ 78.9321,  97.6889],
        [120.2735, 128.0212],
        [ 30.6349,  45.9438],
        [ 93.4100, 111.1781]], grad_fn=<AddmmBackward0>)

In [32]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [33]:
result=model(torch.tensor([[70,60,50.]]))

In [34]:
for apple,orange in result:
    print(apple)
    print(orange)


tensor(54.9710, grad_fn=<UnbindBackward0>)
tensor(70.7368, grad_fn=<UnbindBackward0>)


In [35]:
print("the total rate of apple yeilded is : {} ,and the orange yeilded is : {}".format(apple,orange))

the total rate of apple yeilded is : 54.97104263305664 ,and the orange yeilded is : 70.7367935180664
